### ISSUE TITLE
SwapChain Creation Failed!

### ISSUE THREAD

**Issue by HODAKdev** [benanil/Castle-Engine#1]
I would like to test your engine but I get this error, why do I get this error?
![image](https://user-images.githubusercontent.com/82084934/151665321-a2400479-ac17-4871-80e8-86d47a2bf655.png)

**Comment by benanil** [comment]
DX_CREATE macro creates any struct and fills with 0. ```#define DX_CREATE(_type, _name) _type _name{}; memset(&_name, 0,sizeof(_type));``` I will push a commit maybe your problem fixed

**Comment by HODAKdev** [comment]
I know, I only noticed it after that, that's why I changed issue name. Thanks you.

**Comment by benanil** [comment]
I will send you full project with .rar file I'm uploading

**Comment by benanil** [comment]
Rendering.hpp somehow deleted if you have can you send me?

**Comment by benanil** [comment]
oh I found it

**Comment by HODAKdev** [comment]
yes you can send me a .rar :)

**Comment by HODAKdev** [comment]
VS wrote more warnings..
![img](https://user-images.githubusercontent.com/82084934/151670488-59cd5cbf-77f4-4e32-809a-5ee12cd3546b.png)

**Comment by benanil** [comment]
what is your gpu

**Comment by HODAKdev** [comment]
I have GTX 1650, I'll try it on integrated graphics.

**Comment by HODAKdev** [comment]
Does not work on integrated graphics either.

**Comment by benanil** [comment]
hmm integrated maybe don't support 8x msaa but 1650 must support 8x msaa. however my upload speed is realy slow rar that I will send you must work.

**Comment by benanil** [comment]
errors are about multisampling

> VS wrote more warnings.. ![img](https://user-images.githubusercontent.com/82084934/151670488-59cd5cbf-77f4-4e32-809a-5ee12cd3546b.png)

**Comment by HODAKdev** [comment]
You were right it's because of the MSAA, I adjusted it a bit and I managed to fix it but I get new error dialog boxes.

**Comment by HODAKdev** [comment]
It would probably require automatic adjustment multisampling.

**Comment by benanil** [comment]
https://drive.google.com/file/d/1kf_h4RO5ItHq47FAr_mLXaN5bzn5u9oK/view?usp=sharing

**Comment by HODAKdev** [comment]
It doesn't work, I'm getting the same error `SwapChain Creation Failed!.` I'll try to fix other bugs..

**Comment by HODAKdev** [comment]
I repaired it!
![img](https://user-images.githubusercontent.com/82084934/151678786-e8f8badf-0295-4a29-b450-8dd6b74cff2e.png)
The error was everywhere you used 8x multisampling, i don't know why it doesn't work on my GPU.

**Comment by benanil** [comment]
welll done! this engine is still in development you can contribute

**Comment by HODAKdev** [comment]
Thanks again for the help and I close it :)

**Comment by HODAKdev** [comment]
Thanks again for the help and I close it :)
