### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [benanil/Castle-Engine#2]
.

**Comment by benanil** [comment]
hmm, Nvidia HBAO+ SSAO is not supported on your machine, what is your GPU?
I'have AMD card and it works properly with it. maybe you have integrated GPU?

**Comment by Dunk-Master** [comment]
![image](https://github.com/benanil/Castle-Engine/assets/126705166/c71fd8f5-a57c-4bec-8e53-1f96e82a9c9a)
![image](https://github.com/benanil/Castle-Engine/assets/126705166/113d86d4-606b-496e-bcde-3d31cccd404f)
you also have alot of files missing in your setup
